---
spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_methods'"
.travis.yml:
  extras:
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/centos-7 PUPPET_INSTALL_TYPE=foss PUPPET_INSTALL_VERSION=3.8.7
    services: docker
    sudo: required
    bundler_args: --without development
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04 PUPPET_INSTALL_TYPE=foss PUPPET_INSTALL_VERSION=3.8.7
    services: docker
    sudo: required
    bundler_args: --without development
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/centos-7 PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.5.1
    services: docker
    sudo: required
    bundler_args: --without development
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/debian-8 PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.5.1
    services: docker
    sudo: required
    bundler_args: --without development
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04 PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.5.1
    services: docker
    sudo: required
    bundler_args: --without development
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 PUPPET_INSTALL_TYPE=agent PUPPET_INSTALL_VERSION=1.5.1
    services: docker
    sudo: required
    bundler_args: --without development
  secure: "OKYO+/kY1KB9EH0pB30AU6E2c5SZbNql+Klg+sb1/LMi+ADjyNEzcfTP6aUhnYedKJf5m8rfycc81UPuUeKaR/U/mPwR1R5OKh+S1KL1yzrRdxdpmLWMX14nBFbAZYvSTe/bPbxhngjW84uHRF2zkkSxKStsIzyy2DcTYayaWZ0="
